apiVersion: v2
description: worker chart
name: app-worker
version: 0.1.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x

  - name: someblackmagic-common
    repository: https://someblackmagic.github.io/helm-charts
    tags:
      - someblackmagic-common
    version: 0.x.x
maintainers:
  - name: Andrii Cherny
    url: https://github.com/wirwolf
