apiVersion: v2
description: app-shared-resources
name: app-shared-resources
version: 0.2.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
    tags:
      - bitnami-common

  - name: someblackmagic-common
    repository: https://someblackmagic.github.io/helm-charts
    version: 0.x.x
    tags:
      - someblackmagic-common
maintainers:
  - name: Andrii Cherny
    url: https://github.com/wirwolf
